# Generated by Django 5.2 on 2025-04-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
