# Generated by Django 5.2 on 2025-04-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeminders', '0002_reminder_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
